src/odyssey/legacy/forms/doctor.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, DateField, FloatField, \
                    IntegerField, StringField, TextAreaField


class MedicalHistoryForm(FlaskForm):
    dob = DateField('Date of birth')

    healthcare_contact = StringField('Primary healthcare provider name')
    healthcare_phone = StringField('Primary healthcare provider phone')

    last_examination_date = DateField('Last doctor\'s visit')
    last_examination_reason = StringField('Reason for last visit')

    goals = TextAreaField('Goals')
    concerns = TextAreaField('Health concerns or conditions')
    family_history = TextAreaField('Family history')
    social_history = TextAreaField('Social history including smoking, drinking, and drug use')
    allergies = TextAreaField('Allergies and reactions')
    medication = TextAreaField('Current medication and supplements (include dosage)')

    diagnostic_xray = StringField('X-ray')
    diagnostic_ctscan = StringField('CT scan')
    diagnostic_endoscopy = StringField('Endoscopy or colonoscopy')
    diagnostic_mri = StringField('MRI')
    diagnostic_ultrasound = StringField('Ultrasound')
    diagnostic_other = StringField('Other diagnostic testing')


class MedicalPhysicalExamForm(FlaskForm):
    vital_heartrate = IntegerField('Heart rate')
    vital_respiratoryrate = IntegerField('Respiratory rate')
    vital_systolic = IntegerField('Systolic blood pressure')
    vital_diastolic = IntegerField('Diastolic blood pressure')
    vital_temperature = FloatField('Temperature')
    vital_weight = FloatField('Weight')
    vital_height = StringField('Height (type as string)')

    cardiac_rrr = BooleanField('RRR')
    cardiac_s1s2 = BooleanField('S1S2')
    cardiac_murmurs = BooleanField('Murmurs')
    cardiac_murmurs_info = StringField()
    cardiac_rubs = BooleanField('Rubs')
    cardiac_gallops = BooleanField('Gallops')

    pulmonary_clear = BooleanField('Clear to auscultation bilaterally')
    pulmonary_wheezing = BooleanField('Wheezing')
    pulmonary_wheezing_info = StringField()
    pulmonary_rales = BooleanField('Rales')
    pulmonary_rhonchi = BooleanField('Rhonchi')

    abdominal_soft = BooleanField('Soft')
    abdominal_hard = BooleanField('Non tender')
    abdominal_bowel = BooleanField('Positive bowel sounds')
    abdominal_hsm = BooleanField('Hepatosplenomegaly')
    abdominal_hsm_info = StringField()

    notes = TextAreaField('Other notes')

src/odyssey/legacy/views/doctor.py
from flask import render_template, Blueprint, session, redirect, request, url_for

from odyssey import db
from odyssey.forms.doctor import MedicalHistoryForm, MedicalPhysicalExamForm
from odyssey.models.doctor import MedicalHistory, MedicalPhysicalExam
from odyssey.models.client import ClientInfo

bp = Blueprint('doctor', __name__)

@bp.route('/history', methods=('GET', 'POST'))
def history():
    clientid = session['clientid']
    ci = ClientInfo.query.filter_by(clientid=clientid).one()
    md = MedicalHistory.query.filter_by(clientid=clientid).one_or_none()

    # Map column_names to nested subform.name
    # table2form = {
    #     'diagnostic': {},
    #     'general': {},
    #     'blood': {},
    #     'digestive': {},
    #     'skeletal': {},
    #     'immune': {},
    #     'surgery': {},
    #     'uro': {},
    #     'respiratory': {},
    #     'neuro': {},
    #     'trauma': {},
    #     'nutrition': {}
    # }
    #
    # if md:
    #     for col in md.__table__.c:
    #         parts = col.name.split('_')
    #         if len(parts) > 1 and parts[0] in table2form:
    #             table2form[parts[0]][parts[1]] = getattr(md, col.name, '')

    form = MedicalHistoryForm(
        obj=md,
        dob=ci.dob,
        healthcare_contact=ci.healthcare_contact,
        healthcare_phone=ci.healthcare_phone
    )

    if request.method == 'GET':
        return render_template('doctor/history.html', form=form)

    form = dict(request.form)

    # Error if date = ""
    # TODO: this should be fixed with better input validation
    if not form['last_examination_date']:
        form['last_examination_date'] = None

    if md:
        md.update(form)
    else:
        md = MedicalHistory(clientid=clientid)
        md.update(form)
        db.session.add(md)

    db.session.commit()

    return redirect(url_for('.physical'))

@bp.route('/physical', methods=('GET', 'POST'))
def physical():
    clientid = session['clientid']
    ci = ClientInfo.query.filter_by(clientid=clientid).one()
    md = MedicalPhysicalExam.query.filter_by(clientid=clientid).one_or_none()

    form = MedicalPhysicalExamForm(obj=md)

    if request.method == 'GET':
        return render_template('doctor/physical.html', form=form)

    if md:
        form.populate_obj(md)
    else:
        md = MedicalPhysicalExam(clientid=clientid)
        form.populate_obj(md)
        db.session.add(md)

    db.session.commit()

    return redirect(url_for('main.index'))

src/odyssey/legacy/templates/doctor/history.html
{% extends 'base.html' %}
{% block title %}Medical history{% endblock %}
{% block content %}
<form class="input" method="POST" action="{{ url_for('doctor.history') }}"
        oninput="ageout.value = age(new Date(dob.value));">
    <div class="row">
        <span class="label">{{ form.dob.label }}</span>
        <span class="field">{{ form.dob() }}&nbsp;&nbsp;Age:&nbsp;<output name="ageout"></span>
    </div>
    <div class="row">
        <span class="label">{{ form.healthcare_contact.label }}</span>
        <span class="field">{{ form.healthcare_contact() }}</span>
    </div>
    <div class="row">
        <span class="label">{{ form.healthcare_phone.label }}</span>
        <span class="field">{{ form.healthcare_phone() }}</span>
    </div>
    <div class="row">&nbsp;</div>
    <div class="row">
        <span class="label">{{ form.last_examination_date.label }}</span>
        <span class="field">{{ form.last_examination_date() }}</span>
    </div>
    <div class="row">
        <span class="label">{{ form.last_examination_reason.label }}</span>
        <span class="field">{{ form.last_examination_reason() }}</span>
    </div>
    <div class="row">&nbsp;</div>
    <div class="row">
        <span class="label">{{ form.goals.label }}</span>
        <span class="field">{{ form.goals(rows=5) }}</span>
    </div>
    <div class="row">
        <span class="label">{{ form.concerns.label }}</span>
        <span class="field">{{ form.concerns() }}</span>
    </div>
    <div class="row">
        <span class="label">{{ form.family_history.label }}</span>
        <span class="field">{{ form.family_history() }}</span>
    </div>
    <div class="row">
        <span class="label">{{ form.social_history.label }}</span>
        <span class="field">{{ form.social_history() }}</span>
    </div>
    <div class="row">
        <span class="label">{{ form.allergies.label }}</span>
        <span class="field">{{ form.allergies() }}</span>
    </div>
    <div class="row">
        <span class="label">{{ form.medication.label }}</span>
        <span class="field">{{ form.medication() }}</span>
    </div>

    <h1>Diagnostic history</h1>
    {% for element in (form.diagnostic_xray, form.diagnostic_ctscan,
                       form.diagnostic_endoscopy, form.diagnostic_mri,
                       form.diagnostic_ultrasound, form.diagnostic_other) %}
    {{ macros.expandbox(element) }}
    {% endfor %}
    <div class="row">&nbsp;</div>
    <div class="row center"><button type="submit">Next</button></div>
</form>
<script>
    window.onload = function(){
        var ageout = document.getElementsByName('ageout')[0];
        var dob = document.getElementsByName('dob')[0];
        ageout.value = age(new Date(dob.value));
    }
</script>
{% endblock %}

src/odyssey/legacy/templates/doctor/physical.html
{% extends 'base.html' %}
{% block title %}Physical exam{% endblock %}
{% block content %}
<form class="input" method="POST" action="{{ url_for('doctor.physical') }}">
    <h1>Vitals</h1>
    {% for element in (form.vital_heartrate, form.vital_respiratoryrate,
                       form.vital_systolic, form.vital_diastolic, form.vital_temperature,
                       form.vital_weight, form.vital_height) %}
    <div class="row">
        <span class="label">{{ element.label }}</span>
        <span class="field">{{ element() }}</span>
    </div>
    {% endfor %}
    <h1>Cardiac</h1>
    {% for element in (form.cardiac_rrr, form.cardiac_s1s2, form.cardiac_murmurs,
                       form.cardiac_rubs, form.cardiac_gallops) %}
    <div class="row">
        <span class="radiofield">{{ element() }}</span>
        <span class="radiolabel">{{ element.label }}</span>
    </div>
    {% if element == form.cardiac_murmurs %}
    <div class="row">
        <span class="radiofield"></span>
        <span class="radiolabel">{{ form.cardiac_murmurs_info }}</span>
    </div>
    {% endif %}
    {% endfor %}
    <h1>Pulmonary</h1>
    {% for element in (form.pulmonary_clear, form.pulmonary_wheezing, 
                       form.pulmonary_rales, form.pulmonary_rhonchi) %}
    <div class="row">
        <span class="radiofield">{{ element() }}</span>
        <span class="radiolabel">{{ element.label }}</span>
    </div>
    {% if element == form.pulmonary_wheezing %}
    <div class="row">
        <span class="radiofield"></span>
        <span class="radiolabel">{{ form.pulmonary_wheezing_info }}</span>
    </div>
    {% endif %}
    {% endfor %}
    <h1>Abdominal</h1>
    {% for element in (form.abdominal_soft, form.abdominal_hard,
                       form.abdominal_bowel, form.abdominal_hsm) %}
    <div class="row">
        <span class="radiofield">{{ element() }}</span>
        <span class="radiolabel">{{ element.label }}</span>
    </div>
    {% if element == form.abdominal_hsm %}
    <div class="row">
        <span class="radiofield"></span>
        <span class="radiolabel">{{ form.abdominal_hsm_info }}</span>
    </div>
    {% endif %}
    {% endfor %}
    <h1>General notes</h1>
    <div class="row">
        <span class="radiofield"></span>
        <span class="radiolabel">{{ form.notes() }}</span>
    </div>
    <div class="row">&nbsp;</div>
    <div class="row center"><button type="submit">Save</button></div>
</form>
{% endblock %}