src/odyssey/legacy/forms/intake.py
from datetime import date

from flask_wtf import FlaskForm
from wtforms import BooleanField, DateField, FloatField, HiddenField, RadioField, StringField, SelectField

from odyssey.constants import COUNTRIES, GENDERS, USSTATES, CONTACT_METHODS, YESNO, BOOLIFY

today = date.today()
next_year = date(year=today.year + 1, month=today.month, day=today.day)

class ClientInfoForm(FlaskForm):
    firstname = StringField('First name')
    middlename = StringField('Middle name(s)')
    lastname = StringField('Last name')
    s1 = HiddenField(id='spacer')

    guardianname = StringField('Parent or guardian name (if applicable)')
    guardianrole = StringField('Parent or guardian relationship')

    s2 = HiddenField(id='spacer')
    street = StringField('Address')
    city = StringField('City')
    state = SelectField('State', choices=USSTATES, default='AZ')
    zipcode = StringField('Zip')
    country = SelectField('Country', choices=COUNTRIES, default='US')

    s3 = HiddenField(id='spacer')
    email = StringField('Email address') 
    phone = StringField('Phone')
    preferred = SelectField('Preferred method of contact', choices=CONTACT_METHODS)

    s4 = HiddenField(id='spacer')
    ringsize = FloatField('Ringsize for Oura Ring')

    s5 = HiddenField(id='spacer')
    emergency_contact = StringField('Emergency contact name')
    emergency_phone = StringField('Emergency contact phone')

    s6 = HiddenField(id='spacer')
    healthcare_contact = StringField('Primary healthcare provider name')
    healthcare_phone = StringField('Primary healthcare provider phone')

    s7 = HiddenField(id='spacer')
    gender = SelectField('Gender', choices=GENDERS)
    dob = DateField('Date of birth')
    profession = StringField('Profession or occupation')


class ClientSignForm(FlaskForm):
    fullname = StringField('Full name')
    guardianname = StringField('Parent or guardian name (if applicable)')
    signdate = DateField('Date', default=today)
    signature = HiddenField()


class ClientConsentForm(ClientSignForm):
    infectious_disease = RadioField(choices=YESNO, coerce=BOOLIFY)


class ClientReleaseForm(ClientSignForm):
    release_by_other = StringField()
    release_to_other = StringField()
    release_of_all = RadioField(choices=((1, 'all'), (0, 'other')),
                        coerce=BOOLIFY,
                        default=1)
    release_of_other = StringField()
    release_date_from = DateField()
    release_date_to = DateField()
    release_purpose = StringField()

    emergency_contact = StringField('Emergency contact name')
    emergency_phone = StringField('Emergency contact phone')

    dob = DateField('Date of birth')
    address = StringField('Address')
    phone = StringField('Phone', render_kw={'type': 'phone'})
    email = StringField('Email', render_kw={'type': 'email'})


class ClientReceiveForm(FlaskForm):
    receive_docs = BooleanField(default='checked')


class ClientIndividualContractForm(ClientSignForm):
    doctor_consult = BooleanField()
    pt_consult = BooleanField()
    data_monitoring = BooleanField()
    # drinks = BooleanField()

src/odyssey/legacy/views/intake.py
from flask import render_template, Blueprint, session, redirect, request, url_for

from odyssey import db
from odyssey.pdf import to_pdf
from odyssey.forms.intake import ClientInfoForm, ClientConsentForm, ClientReleaseForm, \
                                 ClientSignForm, ClientReceiveForm, \
                                 ClientIndividualContractForm
from odyssey.models.client import ClientInfo, ClientConsent, ClientRelease, ClientPolicies, \
                                  ClientConsultContract, ClientSubscriptionContract, \
                                  ClientIndividualContract

bp = Blueprint('intake', __name__)

@bp.route('/newclient', methods=('GET', 'POST'))
def newclient():
    session['clientid'] = None
    session['clientname'] = ''
    return redirect(url_for('.clientinfo'))

@bp.route('/clientinfo', methods=('GET', 'POST'))
def clientinfo():
    clientid = session.get('clientid')
    ci = ClientInfo.query.filter_by(clientid=clientid).one_or_none()
    form = ClientInfoForm(request.form, obj=ci)

    if request.method =='GET':
        return render_template('intake/clientinfo.html', form=form)

    fullname = f'{request.form["firstname"]} {request.form["lastname"]}'
    address = f'{request.form["street"]}, {request.form["city"]}, {request.form["state"]} {request.form["zipcode"]}'

    if not ci:
        ci = ClientInfo(fullname=fullname, address=address)
        form.populate_obj(ci)
        db.session.add(ci)
        db.session.commit()

        session['clientid'] = ci.clientid
        session['clientname'] = fullname
    else:
        form.populate_obj(ci)
        db.session.commit()

    return redirect(url_for('.consent'))

@bp.route('/consent', methods=('GET', 'POST'))
def consent():
    clientid = session.get('clientid')
    ci = ClientInfo.query.filter_by(clientid=clientid).one()
    cc = ClientConsent.query.filter_by(clientid=clientid).order_by(ClientConsent.revision.desc()).first()

    form = ClientConsentForm(obj=cc, fullname=ci.fullname, guardianname=ci.guardianname)

    if request.method == 'GET':
        return render_template('intake/consent.html', form=form)

    if not cc:
        cc = ClientConsent(clientid=clientid, revision=ClientConsent.current_revision)
        form.populate_obj(cc)
        db.session.add(cc)
    else:
        form.populate_obj(cc)
        cc.revision = docrev
    db.session.commit()

    to_pdf(clientid, ClientConsent, template='intake/consent.html', form=form)
    return redirect(url_for('.release'))

@bp.route('/release', methods=('GET', 'POST'))
def release():
    clientid = session['clientid']
    ci = ClientInfo.query.filter_by(clientid=clientid).one()
    cr = ClientRelease.query.filter_by(clientid=clientid).order_by(ClientRelease.revision.desc()).first()

    form = ClientReleaseForm(obj=cr,
                             fullname=ci.fullname,
                             guardianname=ci.guardianname,
                             emergency_contact=ci.emergency_contact,
                             emergency_phone=ci.emergency_phone,
                             dob=ci.dob,
                             address=ci.address,
                             phone=ci.phone,
                             email=ci.email)

    if request.method == 'GET':
        return render_template('intake/release.html', form=form)

    if not cr:
        cr = ClientRelease(clientid=clientid, revision=ClientRelease.current_revision)
        form.populate_obj(cr)
        db.session.add(cr)
    else:
        form.populate_obj(cr)
        cr.revision = docrev
    db.session.commit()

    to_pdf(clientid, ClientRelease, template='intake/release.html', form=form)
    return redirect(url_for('.policies'))

@bp.route('/policies', methods=('GET', 'POST'))
def policies():
    clientid = session['clientid']
    ci = ClientInfo.query.filter_by(clientid=clientid).one()
    cp = ClientPolicies.query.filter_by(clientid=clientid).order_by(ClientPolicies.revision.desc()).first()

    form = ClientSignForm(obj=cp, fullname=ci.fullname, guardianname=ci.guardianname)

    if request.method == 'GET':
        return render_template('intake/policies.html', form=form)

    if not cp:
        cp = ClientPolicies(clientid=clientid, revision=ClientPolicies.current_revision)
        form.populate_obj(cp)
        db.session.add(cp)
    else:
        form.populate_obj(cp)
        cp.revision = docrev
    db.session.commit()

    to_pdf(clientid, ClientPolicies, template='intake/policies.html', form=form)
    return redirect(url_for('.send'))

@bp.route('/send', methods=('GET', 'POST'))
def send():
    clientid = session['clientid']
    ci = ClientInfo.query.filter_by(clientid=clientid).one()

    if ci.receive_docs is None:
        form = ClientReceiveForm()
    else:
        form = ClientReceiveForm(receive_docs=ci.receive_docs)

    if request.method == 'GET':
        return render_template('intake/send.html', form=form)

    if 'receive_docs' in request.form and request.form['receive_docs']:
        ci.receive_docs = True
    else:
        ci.receive_docs = False
    db.session.commit()

    return redirect(url_for('main.index'))

@bp.route('/consult', methods=('GET', 'POST'))
def consult():
    clientid = session['clientid']
    ci = ClientInfo.query.filter_by(clientid=clientid).one()
    cc = ClientConsultContract.query.filter_by(clientid=clientid).order_by(ClientConsultContract.revision.desc()).first()

    form = ClientSignForm(obj=cc, fullname=ci.fullname, guardianname=ci.guardianname)

    if request.method == 'GET':
        return render_template('intake/consult.html', form=form)

    if not cc:
        cc = ClientConsultContract(clientid=clientid, revision=ClientConsultContract.current_revision)
        form.populate_obj(cc)
        db.session.add(cc)
    else:
        form.populate_obj(cc)
        cc.revision = docrev
    db.session.commit()

    to_pdf(clientid, ClientConsultContract, template='intake/consult.html', form=form)
    return redirect(url_for('main.index'))

@bp.route('/subscription', methods=('GET', 'POST'))
def subscription():
    clientid = session['clientid']
    ci = ClientInfo.query.filter_by(clientid=clientid).one()
    cs = ClientSubscriptionContract.query.filter_by(clientid=clientid).order_by(ClientSubscriptionContract.revision.desc()).first()

    form = ClientSignForm(obj=cs, fullname=ci.fullname, guardianname=ci.guardianname)

    if request.method == 'GET':
        return render_template('intake/subscription.html', form=form)

    if not cs:
        cs = ClientSubscriptionContract(clientid=clientid,
                                        revision=ClientSubscriptionContract.current_revision)
        form.populate_obj(cs)
        db.session.add(cs)
    else:
        form.populate_obj(cs)
        cs.revision = docrev
    db.session.commit()

    to_pdf(clientid, ClientSubscriptionContract, template='intake/subscription.html', form=form)
    return redirect(url_for('main.index'))

@bp.route('/individual', methods=('GET', 'POST'))
def individual():
    clientid = session['clientid']
    ci = ClientInfo.query.filter_by(clientid=clientid).one()
    cs = ClientIndividualContract.query.filter_by(clientid=clientid).order_by(ClientIndividualContract.revision.desc()).first()

    form = ClientIndividualContractForm(obj=cs,
                                        fullname=ci.fullname,
                                        guardianname=ci.guardianname)

    if request.method == 'GET':
        return render_template('intake/individual.html', form=form)

    if not cs:
        cs = ClientIndividualContract(clientid=clientid,
                                      revision=ClientIndividualContract.current_revision)
        form.populate_obj(cs)
        db.session.add(cs)
    else:
        form.populate_obj(cs)
        cs.revision = docrev
    db.session.commit()

    to_pdf(clientid, ClientIndividualContract, template='intake/individual.html', form=form)
    return redirect(url_for('main.index'))

src/odyssey/legacy/templates/intake/clientinfo.html
{% extends 'base.html' %}
{% block title %}Client information{% endblock %}
{% block content %}
{{ macros.makeform(form, 'infoform', url_for('intake.clientinfo'), pdf=pdf)}}
{% endblock %}

src/odyssey/legacy/templates/intake/consent.html
{% extends 'base.html' %}
{% block title %}Consent form{% endblock %}
{% block content %}
<div class="docrev">Document revision: 2020-03-17</div>
<h1>General health care consent</h1>

<p>I request and authorize Modo Bio Health Systems LLC ("Modo Bio") and Modo Bio's affiliated Doctor ("The Doctor"), to provide outpatient care as The Doctor, The Doctor's assistants and designees deem advisable. This care may include, but is not limited to, physical examination, the drawing and testing of blood, medical advice, and prescriptions of medications, supplements, and other therapeutics. I authorize the health care team at Modo Bio to perform other additional or extended services in emergency situations if it may be necessary or advisable in order to preserve my life or health.</p>

<p>I am aware that the practice of medicine is not an exact science and I acknowledge that no guarantees or promises have been made to me with respect to the results of any diagnostic procedure or treatment.</p>

<h1>Informed consent to physical therapy services</h1>

<p><strong>Cooperation with treatment</strong>: In order for physical therapy treatment to be effective, I must come to scheduled appointments unless there are unusual circumstances. I understand and agree to cooperate with and perform the home physical therapy program intended for me. If I have trouble with any part of my treatment program, I will discuss it with my therapist.</p>

<p><strong>Informed consent for treatment</strong>: The term "informed consent" means that the potential risks, benefits and alternatives of physical therapy treatment have been explained to me. The therapist provides a wide range of services and I understand that I will receive information at the initial visit concerning the treatment and options available for my condition.</p>

<p><strong>No warranty</strong>: I understand that there are no guarantees regarding a cure for or improvement in my condition.</p>

<p><strong>Potential risks</strong>: I may experience an increase in my current level of pain or discomfort, or an aggravation of my existing injury or condition. This discomfort is usually temporary; if it does not subside in a reasonable time period, I agree to contact my physical therapist.</p>

<p><strong>Potential benefits</strong>: I may experience an improvement in my symptoms and an increase in my ability to perform daily activities. I may experience increased strength, awareness, flexibility, and endurance in my movements. I may experience decreased pain and discomfort. I should gain greater knowledge about managing my condition and the resources available to me.</p>

<h1>Informed consent to Intramuscular Manual Therapy/Functional Dry Needling (IMT/FDN)</h1>

<p>IMT/FDN is a valuable treatment for musculoskeletal related pain such as soft tissue and joint pain, as well as to increase muscle performance. IMT/FDN involves placing a small needle into the muscle at the trigger point which is typically in an area in which the muscle is tight and may be tender with the intent of causing the muscle to contract and then release, improving the flexibility of the muscle and therefore decreasing the symptoms. The performing therapist will not stimulate any distal or auricular points during the dry needling treatment.</p>

<p><strong>Risks of the procedure</strong>: Though unlikely, there are risks associated with this treatment. The most serious risk is accidental puncture of a lung (pneumothorax). If this were to occur, it may require only a chest X-ray and no further treatment as it can resolve on its own. A more severe lung puncture can require hospitalization and re-inflation of the lung. This is a rare complication and in skilled hands should not be a concern. If you feel any related symptoms, immediately contact your IMT/FDN provider. If a pneumothorax is suspected, you should seek medical attention from your physician or if necessary, go to the nearest emergency department or dial 911.</p>

<p>Other risks may include bruising, infection and nerve injury. Please notify your provider if you have any conditions that can be transferred by blood, require blood anticoagulants or any other conditions that may have an adverse effect to needle punctures. Bruising is a common occurrence and should not be a concern unless you are taking a blood thinner. Significant tissue trauma from IMT/FDN is possible but unlikely.</p>

<h1>Informed consent to participation in physical fitness program</h1>

<p>I understand that my physical fitness program is individually tailored to meet the goals and objectives agreed upon by my personal trainer and myself. I understand, however, that my personal trainer cannot guarantee that I will accomplish the goals that are established.</p>

<p>I understand that my exercise program will involve participation in a number of types of fitness activities. These activities will vary depending upon my established objectives, but will probably include: 1) aerobic activities; 2) muscular endurance and strength building exercises; 3) other activities selected by my personal trainer and agreed upon by me.</p>

<p><strong>Potential Risks</strong>: No exercise program is without inherent risks. Regardless of the care taken by my personal trainer, he cannot guarantee my personal safety. I realize that when participating in any exercises or conditioning activity, there is always a possibility that minor injuries, major injuries, or catastrophic injury/death may occur.</p>

<p><strong>Risks due to alcohol and substance use</strong>: use of alcohol or drugs, whether licit or illicit, can significantly affect my participation in the Modo Bio Program. I understand that the success of the program may be limited significantly if I continue to use illicit drugs and/or alcohol. Because interactions between alcohol or drug use with certain aspects of the Modo Bio program can be catastrophic or potentially fatal, I will be forthcoming regarding any substance use or abuse issues.</p>

<p><strong>Potential Benefits</strong>: I understand that a regular exercise program has been shown to have definite benefits to general health and well-being, both physiological and psychological.</p>

<p>I represent that I am in good physical condition and have no medical reason or impairment that might prevent me from participation in the program. I will fully disclose any health issues or medications that are relevant to participation in an exercise program.</p>

<p>In agreeing to this exercise program:</p>

<ul>
<li>I acknowledge that my participation is voluntary.</li>
<li>I understand the potential risks involved in the exercise program and believe that the potential benefits outweigh those risks.</li>
<li>I give consent to certain physical touching that may be necessary to ensure proper technique and body alignment.</li>
<li>I understand that the achievement of health or fitness goals cannot be guaranteed.</li>
<li>I will cease exercise immediately if I experience unusual discomfort and feel the need to stop.</li>
</ul>

<p>Please consult with your practitioner if you have any questions regarding the treatment above.</p>

<p>Do you have any known disease or infection that can be transmitted through bodily fluids?</p>
<div>
{% for choice in form.infectious_disease %}
    {{ macros.radioinput(choice, formid='signform', pdf=pdf) }} {{ choice.label }}
{% endfor %}
</div>
<p><strong>If you marked yes, please discuss with our practitioner.</strong></p>

<p>I acknowledge receipt of this consent form; that I have reviewed and understood it; that I have had the opportunity to ask questions; and that I consent to the care provided at Modo Bio.</p>

{{ macros.signform(form, 'signform', url_for('intake.consent'), pdf=pdf) }}
{% endblock %}

src/odyssey/legacy/templates/intake/consult.html
{% extends 'base.html' %}
{% block title %}Consultation contract{% endblock %}
{% block content %}
<div class="docrev">Document revision: 2020-04-28</div>
<p>Welcome to Modo Bio, and to your first step in developing a customized, proactive, and natural pathway to your personal health and wellness goals. Modo Bio works with you, to create a highly personal and continuously assessed health and wellness solution, supported by data analysis.</p>

<p>Your initial consultation is your first step toward a highly personalized and sustainable optimization of your well-being, performance, and healthcare. A complete initial consultation costs $700 (plus laboratory costs), and consists of two 1-hour modules:
<ul>
    <li>The <i>Evaluation Module</i> has 3 components:
        <ol>
            <li>Medical and nutritional evaluation with our affiliated Doctor, in the Doctor's independent practice</li>
            <li>Physical movement evaluation with our staff Physical Therapist</li>
            <li>Introduction to the Training Program with our staff Personal Trainer</li>
        </ol>
        Modo Bio will draw blood and potentially other samples for laboratory testing, and may include physical testing for the Training Program.</li>
    <li>The <i>Consultation Module</i> will be scheduled after return and our evaluation of the samples and lab tests. Modo Bio personnel will review your results and establish a data-optimized action plan to optimize your health and wellness.</li></p>
</ul>

<p>You may elect to purchase only the Evaluation Module, in which case the cost is $350 and no blood work or samples will be drawn or evaluated. The Consultation Module is available only with the Evaluation Module as a prerequisite.</p>

<p>I have read and I understand this Initial Consultation Modules Agreement and the Mobo Bio Policies, which I signed on a previous page.</p>

{{ macros.signform(form, 'signform', url_for('intake.consult'), pdf=pdf) }}
{% endblock %}

src/odyssey/legacy/templates/intake/individual.html
{% extends 'base.html' %}
{% block title %}Individual services{% endblock %}
{% block content %}
<div class="docrev">Document revision: 2020-05-13</div>
<p>Individual services may be purchased outside of the subscription plan.</p>
<div class="row">
    <span class="radiofield">{{ form.doctor_consult(form='signform') }}</span>
    <span class="radiolabel">Appointment with our affiliated Doctor: $400 for a 1 hour consultation.</span>
</div>
<div class="row">
    <span class="radiofield">{{ form.pt_consult(form='signform') }}</span>
    <span class="radiolabel">Appointment with our staff Physical Therapist: $275 for a 1 hour consultation.</span>
</div>
<div class="row">
    <span class="radiofield">{{ form.data_monitoring(form='signform') }}</span>
    <span class="radiolabel">Wearable device bio-data monitoring: $30 per month.</span>
</div>
<div class="row">
    <span class="radiofield">{{ form.drinks(form='signform') }}</span>
    <span class="radiolabel">Nutritional supplements: price to be determined when they are available.</span>
</div>

<h1>Notes</h1>
<ul>
    <li>Consultations may take place in person or by video, depending on scheduling.</li>
    <li>The Modo Bio bio-data monitoring program operates through an Oura Ring wearable device. We have found the Oura Ring superior for tracking relevant information, although we may add other wearables to the program in the future.</li>
    <li>You may purchase an Oura Ring directly from Oura, or from Modo Bio.</li>
    <li>You must give Modo Bio access to your wearable device data, which may require you to execute a consent or enter a consent on a website to release your bio-data to us.</li>
    <li>Bio-data analysis may require up to 9 months or more of data gathering to provide useful information.</li>
    <li>Bio-data analysis may be performed by a Modo Bio Team Member, or by third-party contractors.</li>
</ul>

<p>I have read and I understand this Modo Bio Individual Services Agreement and the Mobo Bio Policies, which I signed on a previous page.</p>

{{ macros.signform(form, 'signform', url_for('intake.individual'), pdf=pdf) }}
{% endblock %}

src/odyssey/legacy/templates/intake/policies.html
{% extends 'base.html' %}
{% block title %}Policies{% endblock %}
{% block content %}
<p><strong>Payment</strong>: Modo Bio Health Systems LLC ("Modo Bio") requires payment in advance. Modo Bio will not bill insurance, and you agree to be a cash-pay client, at rates set by Modo Bio. If you choose to submit any insurance claims yourself, you understand that Modo Bio services are out-of-network, and Modo Bio does not promise reimbursement by any insurance provider. Modo Bio accepts payment by cash, electronic transfer, check, or credit card. There is a $25 fee for checks returned for non-sufficient funds.</p>

<p><strong>Cancellation fee</strong>: Modo Bio will charge a cancellation fee of $100 if you cancel an appointment within 24 hours of the scheduled time.</p>

<p><strong>Subscription termination</strong>: Modo Bio subscription automatically renews at the end of the 3-month period for another 3-month period. To terminate the subscription and prevent automatic renewal, you must notify Modo Bio at least 14 days before the date of renewal. If you terminate the subscription agreement before the end of the 3-month period, Modo Bio will charge you the full cost of the month in which the subscription was terminated.</p>

<p><strong>Disputes</strong>: You agree that any disputes arising out of this Agreement shall be arbitrated in Maricopa County, Arizona, under the Arizona Revised Uniform Arbitration Act, A.R.S. &sect;12-3001 et seq., and the then-current American Arbitration Association (AAA) rules. Although the AAA rules shall apply, the arbitration shall not be conducted by or through AAA. Unless we mutually agree on an arbitrator within 30 days of a demand for arbitration, the arbitrator shall be appointed by the Presiding Civil Judge of the Maricopa County Superior Court and shall be an attorney with at least 10 years' experience in healthcare law. The arbitrator shall issue a written, reasoned opinion within 60 days of conducting an arbitration hearing, which shall be binding and non-appealable.</p>

<p><strong>Disclosure of material health information</strong>: Modo Bio clients are required to disclose relevant medical information that could affect the Modo Bio program, any Modo Bio Team Member, or any other Modo Bio client. Your safety, and ours, depends on you providing accurate and complete information on your Client Information form, including any exposure to HIV/AIDS or COVID-19.</p>

<p><strong>Consent to use health information</strong>: You agree to release health information to Modo Bio as provided on the Modo Bio Release of Information form, which must be signed and returned before your first appointment.</p>

<p><strong>Referrals to The Doctor</strong>: Modo Bio has an affiliation with a Doctor ("The Doctor"), who operates an independent medical practice in space subleased from Modo Bio. While The Doctor is part of our team, Modo Bio does not control The Doctor or The Doctor's practice. The Doctor will use independent judgment in evaluating your medical needs.</p>

<p><strong>Scope</strong>: Modo Bio is not a substitute for regular checkups and medical care. You should have a primary care physician on your healthcare team, who can refer you to specialists for any healthcare needs (including behavioral health). Modo Bio uses your health-related information for lifestyle management and improvement, but the Modo Bio program does not replace your need for regular checkups and healthcare services.</p>

<p><strong>Language, translation services, and hearing-impaired clients</strong>: Modo Bio personnel are English-speaking only and cannot communicate effectively in any other language. Non-English-speaking clients must bring an adequate interpreter with them to every appointment, as Modo Bio does not offer translation services. If you require a interpreter but did not bring one with you, your appointment will be canceled. Deaf or hearing-impaired clients should bring their own sign-language interpreters (often family members or friends, for example), provided that the interpreter is skilled enough to communicate detailed healthcare information effectively.</p>

<p><strong>Discharge policy</strong>: Modo Bio may discharge clients for such reasons as non-compliance, outstanding balance or failure to pay on account, being a "no-show" or late arrival, failure to establish an effective relationship, differing healthcare or lifestyle philosophies, disrespecting a Modo Bio Team Member, creating conflict, and so on. Formal discharge from Modo Bio is at our sole discretion.</p>

<p><strong>Alcohol and substance abuse notification</strong>: Abuse of alcohol or drugs, whether licit or illicit, can significantly affect a client's participation in the Modo Bio Program. Clients must understand that their success may be limited significantly if they continue to use illicit drugs and/or alcohol. Because interactions between alcohol or drug use with certain aspects of the Modo Bio program can be catastrophic or potentially fatal, clients must be forthcoming regarding any substance use or abuse issues.</p>

<p><strong>Fragrance-free and quiet environment</strong>: Modo Bio tries to maintain a suitable environment for health optimization, including low-intensity lighting, quiet, and a scent-free environment. Clients must avoid wearing strong odors, whether from perfumes or grooming products. We also ask that clients put their cellphones on vibrate, refrain from talking on your phone while at Modo Bio, and use headphones or earbuds for listening to any electronic device.</p>

<p><strong>Audio and video recording</strong>: Clients may not record any part of their sessions at Modo Bio without permission.</p>

<p><strong>Pregnancy and lactation warning</strong>: Women clients of childbearing age are responsible to let their Modo Bio Team Member know if they are pregnant, may be pregnant, attempting to become pregnant, not practicing reliable birth control or breastfeeding. Clients at all times should keep their Modo Bio Team Member aware of their pregnancy, pregnancy potential, and breastfeeding status.</p>

<p><strong>After-hours policy</strong>: Modo Bio responds to client questions and concerns during regular business hours, Monday to Friday, 9 am to 5 pm. The Client Portal can be used after hours to submit questions; responses to routine questions, however, may take up to 2 business days via the portal and on holidays. Do not submit emergent or urgent medical issues through the Portal. If you have a significant medical issue, you should directly proceed to the nearest emergency department or dial 911.</p>

<p>I have read and I understand this Modo Bio Policies document.</p>

{{ macros.signform(form, 'signform', url_for('intake.policies'), pdf=pdf) }}
{% endblock %}

src/odyssey/legacy/templates/intake/send.html
{% extends 'base.html' %}
{% block title %}Copy of documents{% endblock %}
{% block content %}
<p><i>Would you like to receive a copy of the documents you just signed to your email address?</i></p>

<p>I understand that email is not a secure (encrypted) method of communication. I understand and accept that there are risks associated with unsecured communications, including that these emails could be intercepted or read by other people.</p>

<form class="input" method="POST" action="{{ url_for('intake.send') }}">
<div class="row">
    <span class="radiofield">{{ form.receive_docs() }}</span>
    <span class="radiolabel">Please email me a copy of the signed documents.</span>
</div>
<div class="row center"><button type="submit">Finish</button></div>
</form>
{% endblock %}