src/odyssey/legacy/views/main.py
from flask import render_template, Blueprint, session, redirect, request, url_for, flash
from werkzeug.security import check_password_hash

from odyssey import db
from odyssey.forms.main import StaffLoginForm, ClientSearchForm
from odyssey.models.staff import Staff
from odyssey.models.client import ClientInfo

bp = Blueprint('main', __name__)

@bp.route('/')
def index():
    if not session.get('staffid'):
        return redirect(url_for('.login'))

    if not session.get('clientid'):
        return redirect(url_for('.clientsearch'))

    return render_template('main/index.html')


@bp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        email = request.form['email'].lower()
        staff = Staff.query.filter_by(email=email).one_or_none()

        if staff and check_password_hash(staff.password, request.form['password']):
            session.clear()
            session['staffid'] = staff.staffid
            session['staffname'] = staff.fullname
            return redirect(url_for('.index'))

        flash('Incorrect email or password')

    return render_template('main/login.html', form=StaffLoginForm())

@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('.index'))

@bp.route('/clientsearch', methods=('GET', 'POST'))
def clientsearch():
    if request.method == 'GET':
        return render_template('main/clientsearch.html', form=ClientSearchForm())

    clauses = []
    if request.form['firstname']:
        clauses.append(ClientInfo.firstname.ilike(f'%{request.form["firstname"]}%'))
    if request.form['lastname']:
        clauses.append(ClientInfo.lastname.ilike(f'%{request.form["lastname"]}%'))
    if request.form['phone']:
        clauses.append(ClientInfo.phone.ilike(f'%{request.form["phone"]}%'))
    if request.form['email']:
        clauses.append(ClientInfo.email.ilike(f'%{request.form["email"]}%'))

    clients = ClientInfo.query.filter(db.and_(*clauses)).all()
    
    if not clients:
        flash('Client not found, please try again.')
        return render_template('main/clientsearch.html', form=ClientSearchForm())

    return render_template('main/clientselect.html', clients=clients)

@bp.route('/clientload', methods=('POST',))
def clientload():
    clientid = request.form['clientid']
    ci = ClientInfo.query.filter_by(clientid=clientid).one()

    session['clientid'] = clientid
    session['clientname'] = ci.fullname

    return redirect(url_for('.index'))

src/odyssey/legacy/views/menu.py
""" Recursive navigation menu generation.

A menu is a tuple () of dicts {}.
Each menu item dict has the keywords 'title' and either 'url' or 'submenu'.
The value for 'submenu' is another menu with the same structure.
"""

menu = (
    {'title': 'Intake', 'submenu': (
        {'title': 'Client info', 'url': 'intake.clientinfo'},
        {'title': 'Forms', 'submenu': (
            {'title': 'Consent form', 'url': 'intake.consent'},
            {'title': 'Release form', 'url': 'intake.release'},
            {'title': 'Policies', 'url': 'intake.policies'},
            {'title': 'Send forms', 'url': 'intake.send'})},
        {'title': 'Contracts', 'submenu': (
            {'title': 'Initial consult', 'url': 'intake.consult'},
            {'title': 'Subscription', 'url': 'intake.subscription'},
            {'title': 'Individual services', 'url': 'intake.individual'})}
    )},
    {'title': 'Doctor', 'submenu': (
        {'title': 'Medical history', 'url': 'doctor.history'},
        {'title': 'Physical exam', 'url': 'doctor.physical'}
    )},
    {'title': 'Physical therapist', 'submenu': (
        {'title': 'Therapy history', 'url': 'pt.history'},
        {'title': 'Mobility assessment', 'url': 'pt.mobility'},
        # {'title': 'Consult', 'url': ''}
    )},
    {'title': 'Trainer', 'submenu': ()}
)
""" A simple, nested description of a menu.

The menu will be converted to HTML on start of the app.

:type: tuple(dict)
"""

src/odyssey/legacy/templates/base.html
{% import 'macros.html' as macros %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <link rel="icon" href="{{ url_for('static', filename='icon.svg') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    {# Signature pad script: https://github.com/szimek/signature_pad #}
    <script src="{{ url_for('static', filename='signature_pad.2.3.2.min.js') }}"></script>
    <script src="{{ url_for('static', filename='library.js') }}"></script>
</head>
<body>
{% if session.get('staffid') %}
    <header class="login">
        <span>{{ session.get('staffname') }}</span>
        <form id="logout" action="{{ url_for('main.logout') }}"></form>
        <button type="submit" form="logout">Log out</button>
    </header>
{% endif %}
<header class="main">
    <img src="{{ url_for('static', filename='logo.svg') }}">
    <h1>{{ self.title() }}</h1>
    {% if session.get('staffid') %}
        {% if session.get('clientid') %}
            <div class="client">
                <span class="client">{{ session.get('clientname') }}</span>
                <span class="clientid">ID: {{ '%05d'|format(session.get('clientid')|int) }}</span>
            </div>
            <form id="loadclient" action="{{ url_for('main.clientsearch') }}"></form>
            <button type="submit" form="loadclient">Switch</button>
        {% else %}
            <span class="noclient">No client loaded</span>
            <form id="loadclient" action="{{ url_for('main.clientsearch') }}"></form>
            <button type="submit" form="loadclient">Load</button>
        {% endif %}
    {% endif %}
</header>
{% if session.get('staffid') %}{% include 'menu.html' %}{% endif %}
<section class="content">
    {% for message in get_flashed_messages() %}
        <div class="flash">{{ message }}</div>
    {% endfor %}
    {% block content %}{% endblock %}
</section>
</body>
</html>

src/odyssey/legacy/templates/macros.html
{# Returns a text box.
    If pdf=True, returns a <div class="textinput"> which is visually similar
    to <input type="text">.

    field: wtforms.StringField object
    formid: if this input is generated outside of <form>, give the formid it belongs to
    pdf: set to True if the output is to be rendered as a PDF.
#}
{% macro textinput(field, formid=None, pdf=False) %}
    {% if pdf %}
        <div class="textinput">{{ field.data }}</div>
    {% else %}
        {% if formid %}
            {{ field(form=formid) }}
        {% else %}
            {{ field() }}
        {% endif %}
    {% endif %}
{% endmacro %}

{# Returns a date box.
    If pdf=True, returns a <div class="textinput">.

    field: wtforms.DateField object
    formid: if this input is generated outside of <form>, give the formid it belongs to
    pdf: set to True if the output is to be rendered as a PDF.
#}
{% macro dateinput(field, formid=None, pdf=False) %}
    {% if pdf %}
        {# TODO: date formatting #}
        <div class="textinput">{{ field.data }}</div>
    {% else %}
        {% if formid %}
            {{ field(form=formid) }}
        {% else %}
            {{ field() }}
        {% endif %}
    {% endif %}
{% endmacro %}

{# Returns a select box with options.
    If pdf=True, returns the selected value in a <div class="textbox">.

    field: wtforms.SelectField object
    formid: if this input is generated outside of <form>, give the formid it belongs to
    pdf: set to True if the output is to be rendered as a PDF.
#}
{% macro selectinput(field, formid=None, pdf=False) %}
    {% if pdf %}
        <div class="textbox">{{ field.data }}</div>
    {% else %}
        {% if formid %}
            {{ field(form=formid) }}
        {% else %}
            {{ field() }}
        {% endif %}
    {% endif %}
{% endmacro %}

{# Returns a radio choice field.
    If pdf=True, returns <div class="radio"> (or <div class="radio radio-checked>)
    which is visually similar to <input type="radio">.

    This macro does **NOT** loop over all choices.

    field: wtforms.RadioField object
    formid: if this input is generated outside of <form>, give the formid it belongs to
    pdf: set to True if the output is to be rendered as a PDF.
#}
{% macro radioinput(field, formid=None, pdf=False) %}
    {% if pdf %}
        {% if field.checked %}
            <div class="radio radio-checked"></div>
        {% else %}
            <div class="radio"></div>
        {% endif %}
    {% else %}
        {% if formid %}
            {{ field(form=formid) }}
        {% else %}
            {{ field() }}
        {% endif %}
    {% endif %}
{% endmacro %}

{# Returns a check box.
    If pdf=True, returns a <div class="checkbox"> which is visually similar
    to <input type="check">.

    field: wtforms.BooleanField object
    formid: if this input is generated outside of <form>, give the formid it belongs to
    pdf: set to True if the output is to be rendered as a PDF.
#}
{% macro checkinput(field, formid=None, pdf=False) %}
    {% if pdf %}
        {% if field.data %}
            <div class="checkbox checkbox-checked"></div>
        {% else %}
            <div class="checkbox"></div>
        {% endif %}
    {% else %}
        {% if formid %}
            {{ field(form=formid) }}
        {% else %}
            {{ field() }}
        {% endif %}
    {% endif %}
{% endmacro %}

{# An expanding checkbox
    Generates a checkbox with a label that, when checked, expands a textbox
    for further information.

    If the checkbox is checked, but nothing is entered in the textbox, then
    nothing is stored. The checked state of the checkbox itself is not stored.

    element: StringField
#}
{% macro expandbox(element) %}
    <div class="expandformrow">
        <input class="expandform" type="checkbox" id="{{ element.name }}"
            {% if element.data %}checked{% endif %}>
        <label class="expandform" for="{{ element.name }}">{{ element.label }}</label>
        <div class="expandform">
            {{ element() }}
        </div>
    </div>
{% endmacro %}

{# A canvas with a signature pad.
    If pdf=True, returns <img class="sigpad"> with the PNG contents of the signature.

    field: wtforms.HiddenField object that holds the signature data
            as a mime-type + base64 encoded string.
    id: the id of the signature canvas.
    formid: the id of the form that holds the signature pad.
    pdf: set to True if the output is to be rendered as a PDF.
#}
{% macro signatureinput(field, id, formid, pdf=False) %}
    {% if pdf %}
    <img class="sigpad" src="{{ field.data }}">
    {% else %}
    <canvas class="sigpad" id="{{ id }}"></canvas>
    <div class="row right"><button id="{{ id }}-clear" type="button">Clear</button></div>
    <script>add_signature_pad('{{ id }}', '{{ formid }}', '{{ id }}-clear', '{{ field.name }}');</script>
    {% endif %}
{% endmacro %}

{# Generic form generator. Loops over all input fields to generate them.
    If pdf=True, will generate the PDFable versions.

    form: the wtforms.Form object.
    id: unique id for this form.
    endpoint_url: URL for this form on submit (give as url_for(endpoint.name)).
    pdf: set to True if the output is to be rendered as a PDF.
#}
{% macro makeform(form, id, endpoint_url, submit='Next', pdf=False) %}
    <form id="{{ id }}" class="input" method="POST" action="{{ endpoint_url }}">
    {% for field in form %}
    <div class="row">
    {%   if field.type in ('StringField', 'DecimalField', 'IntegerField', 'FloatField') %}
        <span class="label">{{ field.label }}</span>
        <span class="field">{{ textinput(field, pdf=pdf) }}</span>
    {% elif field.type == 'DateField' %}
        <span class="label">{{ field.label }}</span>
        <span class="field">{{ dateinput(field, pdf=pdf) }}</span>
    {% elif field.type == 'SelectField' %}
        <span class="label">{{ field.label }}</span>
        <span class="field">{{ selectinput(field, pdf=pdf) }}</span>
    {% elif field.type == 'RadioField' %}
        {% for subfield in field %}
            <span class="radiofield">{{ radioinput(subfield, pdf=pdf) }}</span>
            <span class="radiolabel">{{ subfield.label }}</span>
        {% endfor %}
    {% elif field.type == 'BooleanField' %}
        <span class="radiofield">{{ checkinput(field, pdf=pdf) }}</span>
        <span class="radiolabel">{{ field.label }}</span>
    {% elif field.type == 'HiddenField' and field.id == 'spacer' %}
        &nbsp;
    {% else %}
        {# TODO: figure out if CSRF tokens need to be rendered #}
        {{ field() }}
    {% endif %}
    </div>
    {% endfor %}
    <div class="row center"><button type="submit">{{ submit }}</button></div>
    </form>
{% endmacro %}

{# Signature form generator.
    If pdf=True, will generate the PDFable versions.

    form: the wtforms.Form object.
    id: unique id for this form.
    endpoint_url: URL for this form on submit (give as url_for(endpoint.name)).
    pdf: set to True if the output is to be rendered as a PDF.
#}
{% macro signform(form, id, endpoint_url, pdf=False) %}
    {% if not pdf %}
    <form id="{{ id }}" class="input" method="POST" action="{{ endpoint_url }}">
    {{ form.signature() }}
    {% endif %}
    <div class="row">
        <span class="label">{{ form.signdate.label }}</span>
        <span class="field">{{ textinput(form.signdate, pdf=pdf) }}</span>
    </div>
    <div class="row">
        <span class="label">{{ form.fullname.label }}</span>
        <span class="field">{{ textinput(form.fullname, pdf=pdf) }}</span>
    </div>
    <div class="row">
        <span class="label">{{ form.guardianname.label }}</span>
        <span class="field">{{ textinput(form.guardianname, pdf=pdf) }}</span>
    </div>
    <div class="row">
        <span class="label">Signature</span>
        <span class="field">{{ signatureinput(form.signature, 'sigpad', id, pdf=pdf) }}</span>
    </div>
    {% if not pdf %}
    <div class="row">&nbsp;</div>
    <div class="row center"><button type="submit">Accept</button></div>
    </form>
    {% endif %}
{% endmacro %}

src/odyssey/legacy/templates/menu.html
<nav>
<div class="menu-bar">
    <label for="menu-button">
        <img class="menu-icon" src="{{ url_for('static', filename='menu-icon.svg') }}">
    </label>
    <input type="checkbox" class="menu-button" id="menu-button">
    <div class="menu">
        {% for item in menu recursive %}
        {% if 'submenu' in item %}
            <label for="menu-button-{{ loop.depth0 }}-{{ loop.index0 }}"
                   class="menuitem submenu-depth-{{ loop.depth }}">
                {{ item.title }}
            </label>
            <input id="menu-button-{{ loop.depth0 }}-{{ loop.index0 }}"
                   class="menu-button"
                   type="checkbox">
            <div class="submenu submenu-depth-{{ loop.depth }}">
                {{ loop(item.submenu) }}
            </div>
        {% else %}
            <span class="submenuitem">
                <a href="{{ url_for(item.url) }}">{{ item.title }}</a>
            </span>
        {% endif %}
        {% endfor %}
        </div>
    </div>
</div>
</nav>