src/odyssey/legacy/forms/pt.py
from datetime import datetime

from flask_wtf import FlaskForm
from wtforms import BooleanField, FormField, HiddenField, IntegerField, StringField, TextAreaField


class PTHistoryForm(FlaskForm):
    exercise = TextAreaField('Please describe your current exercise routine, how often, and where/with whom. Leave empty if you do not exercise.')

    has_pt = BooleanField('Physical therapy')
    has_chiro = BooleanField('Chiropractor')
    has_massage = BooleanField('Massage therapy')
    has_surgery = BooleanField('Surgery')
    has_medication = BooleanField('Medication')
    has_acupuncture = BooleanField('Acupuncture')

    pain_areas = HiddenField()

    best_pain = IntegerField('Best pain')
    worst_pain = IntegerField('Worst pain')
    current_pain = IntegerField('Current pain')

    makes_worse = StringField('What makes your symptoms worse, including time of day?')
    makes_better = StringField('What makes your symptoms better, including time of day?')


class MobilityAssessmentQuadrantForm(FlaskForm):
    er = IntegerField('ER')
    ir = IntegerField('IR')
    abd = IntegerField('ABD')
    add = IntegerField('ADD')
    flexion = IntegerField('Flexion')
    extension = IntegerField('Extension')


class MobilityAssessmentLSForm(MobilityAssessmentQuadrantForm):
    title = 'Left shoulder'


class MobilityAssessmentRSForm(MobilityAssessmentQuadrantForm):
    title = 'Right shoulder'


class MobilityAssessmentLHForm(MobilityAssessmentQuadrantForm):
    title = 'Left hip'


class MobilityAssessmentRHForm(MobilityAssessmentQuadrantForm):
    title = 'Right hip'


class MobilityAssessmentForm(FlaskForm):
    timestamp = StringField('Assessment date', default=datetime.now())
    isa_left = IntegerField('ISA left')
    isa_right = IntegerField('ISA right')
    isa_dynamic = BooleanField('Dynamic?')

    left_shoulder = FormField(MobilityAssessmentLSForm, separator='_')
    right_shoulder = FormField(MobilityAssessmentRSForm, separator='_')
    left_hip = FormField(MobilityAssessmentLHForm, separator='_')
    right_hip = FormField(MobilityAssessmentRHForm, separator='_')

src/odyssey/legacy/views/pt.py
from flask import flash, render_template, Blueprint, session, redirect, request, url_for

from odyssey import db
from odyssey.forms.pt import MobilityAssessmentForm, PTHistoryForm
from odyssey.models.pt import MobilityAssessment, PTHistory

bp = Blueprint('pt', __name__)


@bp.route('/history', methods=('GET', 'POST'))
def history():
    clientid = session['clientid']
    pt = PTHistory.query.filter_by(clientid=clientid).one_or_none()

    form = PTHistoryForm(obj=pt)

    if request.method == 'GET':
        return render_template('pt/history.html', form=form)

    form = dict(request.form)
    for k in ('has_pt', 'has_chiro', 'has_massage', 'has_surgery',
              'has_medication', 'has_acupuncture'):
        if k in form and form[k]:
            form[k] = True
        else:
            form[k] = False

    if pt:
        pt.update(form)
    else:
        pt = PTHistory(**form, clientid=clientid)
        db.session.add(pt)

    db.session.commit()

    return redirect(url_for('.mobility'))

@bp.route('/mobility', methods=('GET', 'POST'))
def mobility():
    clientid = session['clientid']
    mb = MobilityAssessment.query.filter_by(clientid=clientid).one_or_none()

    # Map column_names to nested subform.name
    table2form = {
        'left_shoulder': {},
        'right_shoulder': {},
        'left_hip': {},
        'right_hip': {}
    }

    if mb:
        for col in mb.__table__.c:
            parts = col.name.split('_')
            if len(parts) == 3:
                subform = parts[0] + '_' + parts[1]
                element = parts[2]
                table2form[subform][element] = getattr(mb, col.name, '')

    form = MobilityAssessmentForm(obj=mb, **table2form)

    if request.method == 'GET':
        flash('This needs some type of load/save functionality to recall previous assessments and scroll through them.')
        return render_template('pt/mobility.html', form=form)

    form = dict(request.form)

    isa = False
    if 'isa_dynamic' in form and form['isa_dynamic']:
        form['isa_dynamic'] = True
    else:
        form['isa_dynamic'] = False

    if mb:
        mb.update(form)
    else:
        mb = MobilityAssessment(**form, clientid=clientid)
        db.session.add(mb)

    db.session.commit()

    return redirect(url_for('main.index'))

src/odyssey/legacy/templates/pt/history.html
{% extends 'base.html' %}
{% block title %}PT history{% endblock %}
{% block content %}
<form id="pthistory" class="input" method="POST" action="{{ url_for('pt.history') }}">
    <div class="row">
        <span class="label">{{ form.exercise.label }}</span>
        <span class="field">{{ form.exercise() }}</span>
    </div>
    <div class="row">&nbsp;</div>
    <div class="row">
        <span class="label">Please indicate if you have received any of the following treatments.</span>
        <span class="field">
            <div class="multicol">
                {% for treatment in ( form.has_pt, form.has_chiro, form.has_massage,
                                      form.has_surgery, form.has_medication,
                                      form.has_acupuncture) %}
                <div class="row">
                    <span class="radiofield">{{ treatment() }}</span>&ensp;
                    <span class="radiolabel">{{ treatment.label }}</span>
                </div>
                {% endfor %}
            </div>
        </span>
    </div>
    <div class="row">&nbsp;</div>
    <p>Please indicate any areas of pain you are currently experiencing.</p>
    {{ form.pain_areas() }}
    <div class="painarealabel">
        <span>Front</span>
        <span>Back</span>
    </div>
    <div class="painarea">
        <img class="painarea" src="{{ url_for('static', filename='human_silhouette.svg') }}">
        <canvas class="painarea" id="pain"></canvas>
    </div>
    <div class="row center">
        <span>Draw</span>
        <label class="switch">
            <input class="switch" type="checkbox" id="draw">
            <span class="switch"></span>
        </label>
        <span>Erase</span>&emsp;&emsp;&emsp;
        <button id="clear" type="button">Clear</button>
    </div>
    <div class="row">&nbsp;</div>
    <p>Please rate your symptoms on scale of 0 to 10, with 0 = no pain and 10 = the worst pain imaginable, you need to go to the emergency room.</p>
    <div class="row">
        <span class="label">{{ form.best_pain.label }}</span>
        <span class="field">{{ form.best_pain() }}</span>
    </div>
    <div class="row">
        <span class="label">{{ form.worst_pain.label }}</span>
        <span class="field">{{ form.worst_pain() }}</span>
    </div>
    <div class="row">
        <span class="label">{{ form.current_pain.label }}</span>
        <span class="field">{{ form.current_pain() }}</span>
    </div>
    <div class="row">&nbsp;</div>
    <div class="row">
        <span class="label">{{ form.makes_worse.label }}</span>
        <span class="field">{{ form.makes_worse() }}</span>
    </div>
    <div class="row">
        <span class="label">{{ form.makes_better.label }}</span>
        <span class="field">{{ form.makes_better() }}</span>
    </div>
    <div class="row">&nbsp;</div>
    <div class="row center"><button type="submit">Next</button></div>
</form>
<script>add_pain_area_pad('pain', 'pthistory', 'clear', 'draw', '{{ form.pain_areas.id }}');
</script>
{% endblock %}

src/odyssey/legacy/templates/pt/mobility.html
{% extends 'base.html' %}
{% block title %}Mobility assessment{% endblock %}
{% block content %}
<form class="input" method="POST" action="{{ url_for('pt.mobility') }}">
    <div class="row">
        <span class="label">{{ form.timestamp.label }}</span>
        <span class="field">{{ form.timestamp() }}</span>
    </div>
    <div class="row">
        <span class="label">{{ form.isa_left.label }}</span>
        <span class="field">{{ form.isa_left() }}</span>
    </div>
    <div class="row">
        <span class="label">{{ form.isa_right.label }}</span>
        <span class="field">{{ form.isa_right() }}</span>
    </div>
    <div class="row">
        <span class="label">{{ form.isa_dynamic.label }}</span>
        <span class="field">{{ form.isa_dynamic() }}</span>
    </div>
    <div class="row">&nbsp;</div>
    <div class="multicol">
    {% for subform in (form.left_shoulder, form.left_hip, form.right_shoulder, form.right_hip) %}
        <h1>{{ subform.title }}</h1>
        {% for element in subform %}
            {% if element.type == 'IntegerField' %}
            <div class="row">
                <span class="label">{{ element.label }}</span>
                <span class="field">{{ element() }}</span>
            </div>
            {% else %}
            {# Do CSRF tokens need to be generated? #}
            {# {{ element() }} #}
            {% endif %}
        {% endfor %}
    {% endfor %}
    </div>
    <div class="row">&nbsp;</div>
    <div class="row center"><button type="submit">Next</button></div>
</form>
{% endblock %}